# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=100)),
                ('path', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('processed_text', models.TextField(default='')),
                ('file', models.FileField(default=None, upload_to=document.models.get_path)),
            ],
            options={
                'permissions': (('can_view_document', 'Can view document'), ('can_delete_document', 'Can delete document'), ('can_change_document', 'Can change document')),
            },
        ),
    ]
