# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_text', models.TextField(default='')),
                ('file_id', models.CharField(default='', max_length=100)),
                ('author', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='brain.Client')),
            ],
        ),
    ]
