# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20160429_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='telegram_file_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
