# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_document_telegram_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='telegram_file_id',
        ),
    ]
