# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('token', models.CharField(blank=True, max_length=500)),
                ('first_name', models.CharField(blank=True, max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('data', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
    ]
