# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 23:27
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='data',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
