# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_client_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
