# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
